config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'recipes#index'

  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amount.rb
# frozen_string_literal: true

class Amount < ApplicationRecord
  belongs_to :ingredient
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord # :nodoc:
  has_many :recipes_ingredients, dependent: :nullify
  has_many :recipes, through: :recipes_ingredients, dependent: :nullify
  has_one :amount, dependent: :destroy

  accepts_nested_attributes_for :amount, reject_if: :all_blank
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord # :nodoc:
  validates :title, presence: true
  validates :instructions, presence: true
  has_many :recipes_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipes_ingredients, dependent: :destroy

  accepts_nested_attributes_for :ingredients

  belongs_to :user

  def owner?(user)
    user.present? && user == self.user
  end
end

app/models/recipes_ingredient.rb
# frozen_string_literal: true

class RecipesIngredient < ApplicationRecord # :nodoc:
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord # :nodoc:
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == 'admin'
  end

  def default?
    role == 'default'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :set_locale
  after_action :verify_authorized, unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  private

  def user_not_authorized
    flash[:alert] = I18n.t('not_authorized')
    redirect_to(request.referer || root_path)
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = Recipe.all
    authorize @recipes
  end

  def show; end

  def new
    @recipe = Recipe.new
    authorize @recipe
  end

  def edit; end

  def create
    @recipe = Recipe.new(recipe_params)
    authorize @recipe

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
    authorize @recipe
  end

  def recipe_params
    params.require(:recipe).permit(
      :title, :work_duration, :cooking_duration, :difficulty, :instructions,
      :user_id, ingredients_attributes: [:id, :title, :_destroy, amount_attributes: %i[value unit]]
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/amounts/_amount_fields.haml
.nested_fields
  = f.input :value
  = f.input :unit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title Recipes
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no' }
  %body
    .navbar.navbar-expand-lg.navbar-light.bg-light
      %a.navbar-brand
        = link_to t(:recipes), recipes_path, class: 'item'
      %button.navbar-toggler{ type: :button, data: { toggle: :collapse, target: '#navbar-supported-content' }, aria: { controls: 'navbar-supported-content', expanded: false, label: 'Toggle Navigation' } }
        %span.navbar-toggler-icon
      .collapse.navbar-collapse#navbar-supported-content
        %ul.navbar-nav.ml-auto
          - if Rails.env.development?
            %li.nav-item.dropdown
              %a.nav-link.dropdown-toggle#navbar-dropdown-dev{ href: '#', role: :button, data: { toggle: :dropdown }, aria: { haspopup: true, expanded: false } }
                Dev
              .dropdown-menu{ aria: { labelledby: 'navbar-dropdown-dev' } }
                = link_to 'Travis', 'https://travis-ci.org/phansch/recipes', class: 'dropdown-item'
                = link_to 'Pull Requests', 'https://github.com/phansch/recipes/pulls', class: 'dropdown-item'
                = link_to 'GitHub Project', 'https://github.com/phansch/recipes/projects/1', class: 'dropdown-item'
                = link_to 'GitHub Project', 'https://github.com/phansch/recipes/projects/1', class: 'dropdown-item'
          %li.nav-item.dropdown
            - if current_user
              %a.nav-link.dropdown-toggle#navbar-dropdown-user{ href: '#', role: :button, data: { toggle: :dropdown }, aria: { haspopup: true, expanded: false } }
                = t('nav.my_account')
              .dropdown-menu{ aria: { labelledby: 'navbar-dropdown-user' } }
                = link_to t('nav.profile'), edit_user_registration_path, class: 'dropdown-item'
                = link_to t('nav.logout'), destroy_user_session_path, class: 'dropdown-item', method: :delete
            - else
              %li.nav-item
                = link_to t('nav.login'), new_user_session_path(current_user), class: 'nav-link'

    .container
      .row
        .col-sm
          - if flash.present?
            #flash-messages
              - flash.each do |type, message|
                .alert.alert-dismissable{ class: "alert-#{type}", role: :alert }
                  = message
                  %button.close{ type: :button, data: { dismiss: :alert }, aria: { label: 'Close' } }
                    %span{ aria: { hidden: true } } &times;
          = yield

app/views/recipes/_form.html.haml
= simple_form_for(@recipe) do |f|
  = f.input :title, as: :string
  %h3 Ingredients
  #ingredients
    = f.simple_fields_for :ingredients do |ingredient|
      = render 'ingredient_fields', f: ingredient
    .links
      = link_to_add_association 'add ingredient', f, :ingredients
  = f.input :work_duration
  = f.input :cooking_duration
  = f.input :difficulty
  = f.input :instructions
  = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
  = f.button :submit

app/views/recipes/_ingredient_fields.haml
.nested_fields
  = f.input :title
  = f.simple_fields_for :amount, f.object.build_amount do |amount|
    = render 'amounts/amount_fields', f: amount
  = link_to_remove_association 'remove ingredient', f

app/views/recipes/edit.html.haml
%h1 Editing recipe

= render 'form'

= link_to 'Show', @recipe
\|
= link_to 'Back', recipes_path

app/views/recipes/index.html.haml
%h1.ui.header Listing recipes

%table
  %thead
    %tr
      %th Title
      %th Work duration
      %th Cooking duration
      %th Difficulty
      %th Instructions
      %th
      %th
      %th

  %tbody
    - @recipes.each do |recipe|
      %tr
        %td= recipe.title
        %td= recipe.work_duration
        %td= recipe.cooking_duration
        %td= recipe.difficulty
        %td= recipe.instructions
        %td= link_to 'Show', recipe
        %td= link_to 'Edit', edit_recipe_path(recipe)
        %td= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Recipe', new_recipe_path

app/views/recipes/new.html.haml
%h1 New recipe

= render 'form'

= link_to 'Back', recipes_path

app/views/recipes/show.html.haml
%p
  %b Title:
  = @recipe.title

%ul
- @recipe.ingredients.each do |i|
  %li
    #{i.amount.value} #{i.amount.unit} #{i.title}

%p
  %b Work duration:
  = @recipe.work_duration
%p
  %b Cooking duration:
  = @recipe.cooking_duration
%p
  %b Difficulty:
  = @recipe.difficulty
%p
  %b Instructions:
  = sanitize @recipe.instructions, tags: %w[em strong a blockquote p], attributes: %w[href]

= link_to 'Edit', edit_recipe_path(@recipe)
\|
= link_to 'Back', recipes_path